stages:
  - build
  - testing

build:deb:
  stage: build
  tags:
    - deb
  before_script:
    - mkdir build
    - cd build
  script:
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF ..
    - cmake --build . --target fsdb -- -j 8
  artifacts:
    paths:
      - build/libfsdb.so

